local apperance = {
	['dude']={
		Font=Enum.Font.JosefinSans,
		Sound=workspace,
		TextColor=Color3.new(0.92549, 1, 0.439216),
		BackgroundColor=Color3.new(0.517647, 0.290196, 0.0156863),
		OutlineColor=Color3.new(0.403922, 0.203922, 0.0862745),
	},
	['player']={
		Font=Enum.Font.Merriweather,
		Sound=workspace,
		TextColor=Color3.new(0, 0, 0),
		BackgroundColor=Color3.new(0.423529, 0.368627, 0.305882),
		OutlineColor=Color3.new(0.403922, 0.317647, 0.270588),
	},
	['wking']={
		Font=Enum.Font.Highway,
		Sound=workspace,
		TextColor=Color3.new(1, 1, 1),
		BackgroundColor=Color3.new(0.701961, 0.701961, 0.701961),
		OutlineColor=Color3.new(0.403922, 0.403922, 0.403922),
	},
	['bqueen']={
		Font=Enum.Font.Highway,
		Sound=workspace,
		TextColor=Color3.new(0, 0, 0),
		BackgroundColor=Color3.new(0.231373, 0.231373, 0.231373),
		OutlineColor=Color3.new(0.317647, 0.317647, 0.317647),
	},
}

return apperance
