local stat = {
	first_place=true
	
	,letter_Speed=25-- high=faster 
	,Line_Wait=1.5 -- IF its auto, how long should you wait to change to a different dialogue
	,Auto=false -- false= beep boop go into visual novel mode 🤖🤖🤖
	,Skip_Intro=false -- PLEASE dont skip my carefully made intro, i worked REALLY hard into itS
	,run=false,
	,Patient=2
	,_Patient=2
	,_PatientMax=3
	,_PatientSnap=0 -- oh no she mad ;-;
	
}

return stat
